language: ruby
rvm:
  - 2.4.1

sudo: false # route your build to the container-based infrastructure for a faster build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false

cache: 
 bundler: true # caching bundler gem packages will speed up build
 apt: true

matrix:
  fast_finish: true

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the master branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - JEKYLL_ENV=production

addons:
  apt:
    packages:
    - libcurl4-openssl-dev


before_install:
  - gem update --system
  - gem install bundler
  

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: 
  - JEKYLL_ENV=production bundle exec jekyll build --safe --verbose --profile
