# Develop override settings
url: http://localhost:3000
local: true

analytics:
  provider: false

sass:
  style: expanded

atom:
  buildCommand:
    - bundle
    - exec
    - jekyll
    - build
  buildEnv:
    JEKYLL_ENV: development
  postDirs:
    - _newsletters
  defaultPostDir: _drafts
  

staticman:
  endpoint               : http://localhost:8080/v2/entry/ # URL of your own deployment with trailing slash, will
  
webmentions:  
#  provider: "jekyll-webmention_io "
#https://webmention.io/dfolio.github.io/webmention
  API_KEY: OEX5Uhxp5sZL_lvLfJ3ruw
  cache_folder: _data/webmentions
  cache_bad_uris_for: 5
  legacy_domains:
    - https://dfolio.github.io/
    - http://dfolio.github.io/
  pause_lookups: false
  pages: false
  collections:
    - pandoc-df-thesis
    - sidebar
  js:
    destination: _data/webmentions/js
    uglify: false
    deploy: false  
