#theme:                      jekyll-theme-tactile
version: 1.2.2
# Global site settings
locale                  :    "en-US"
lang                    :    "en"

title                   :    D.Folio GitHub Pages
title_separator         :    "&mdash;"
name                    :    "D. Folio"
description             :     GitHub-pages to share some various things that D.Folio works on as personal hobbies
keywords                :    dfolio, github, webpage
logo                    :    "/assets/media/logo.png"
theme_color             :    "#ffffff"

# Site settings
baseurl                :     ""
url                    :     "https://dfolio.github.io/"
#github-metadata
repository             :     "dfolio/dfolio.github.io"

encoding:                    "utf-8"
timezone:                    Europe/Paris

# Site links
links: &links
  - label:               "GitHub Page"
    icon:                "fab fa-fw fa-github"
    url:                 "https://dfolio.github.io/"
  - label:               "GitHub Repo"
    icon:                "fab fa-fw fa-github"
    url:                 "https://github.com/dfolio/dfolio.github.io/"
  - label:                 "Facebook"
    icon:                  "fab fa-fw fa-facebook-square"
    # url:
  - label:                 "keybase"
    icon:                  "fab fa-fw fa-keybase"
    url:                   "https://keybase.io/dfolio"
  - label:                 "Website"
    icon:                  "fas fa-fw fa-link"
    url:                   "https://dfolio.fr"

# Site Author
author:
  name             :         "David Folio"
  url              :         "https://dfolio.fr"
  image            : &image  "/assets/media/dfolio.png"
  avatar           : *image
  bio              :         "I am an amazing person."
  location         :         "France"
  links            :         *links

social:
  type: Person
  name: "David Folio"
  links:
    - "https://dfolio.github.io/"
    - "https://dfolio.fr"

webmentions: 
  provider: "webmention.herokuapp.com"
  username: dfolio.github.io

# Site Footer
footer:
  links: *links

#css_cdn:
#  -
#    url:                     "https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css"
#    #hash:                   "sha384-qpNsn9fNAkiBXwcwfxPTn1Ou6UU9P6pYGWQqLRIJOlPsAKOA+8XzN2coCnVnb8Fa"


# See https://www.srihash.org for info on how to generate the hashes
js_cdn:
  - name: mathjax
    url:       "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"
    hash:      "sha384-3lJUsx1TJHt7BA4udB5KPnDrlkO8T6J6v/op7ui0BbCjvZ9WqV4Xm6DTP6kQ/iBH"
    async:    true
    defer:    true
  - name: fontawesome
    url:       "https://use.fontawesome.com/releases/v5.5.0/js/all.js"
    hash:      "sha384-GqVMZRt5Gn7tB9D9q7ONtcp4gtHIUEW/yG7h98J7IpE3kpi+srfFyyB/04OV6pG0"
    async:    true
    defer:    true
  - name: jquery
    url:        "https://code.jquery.com/jquery-3.2.1.slim.min.js"  
    hash:       "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    defer:     true
  - name: popper
    url:        "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" 
    hash:       "sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    defer:      true
  - name: bootstrap
    url:       "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    hash:      "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    defer:     true

google_site_verification : "Kz1t3CXSmXhESbiqvIXWkrMQCKodNkaOW8KazdTKqiI"
# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-464536-9" # Replace this with your ID, or delete
    anonymize_ip         : false

serviceWorker:
  workbox:
    url: https://storage.googleapis.com/workbox-cdn/releases/3.6.1/workbox-sw.js
    version: 1.2.2
feed:
  collections:
    - pandoc-df-thesis

# Collections
collections:
  sidebar:
    output:                  true
    permalink:               /:collection/:path/
  pandoc-df-thesis:
    output:                  true
    permalink:               /docs/:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path:                  ""
      type:                  posts
    values:
      layout:                post
      comments:              true
      edit:                  false
      share:                 true
  # _sidebar
  - scope:
      path:                  ""
      type:                  sidebar
    values:
      layout:                docs
      collection_details:   true
      comments:              true
      edit:                  false
      toc:                   true
      share:                 true
  # _pandoc-df-thesis-template
  - scope:
      path:                  ""
      type:                  pandoc-df-thesis
    values:
      layout:                docs
      toc:                   true
      comments:              false
      collapse:              false
      edit:                  true
      share:                 true

# Build settings


# Outputting
#permalink:                  pretty
permalink:                   /:categories/:title/

#paginate:                   5 # amount of posts to show
#paginate_path:              /page:num/

highlighter:                 rouge
markdown_ext:                "markdown,mkdown,mkdn,mkd,md"
kramdown:
  input:                     GFM
  auto_ids:                  true
  footnote_nr:               1
  toc_levels:                1..6
  enable_coderay:            false
  parse_block_html:          true
  hard_wrap:                 false
  entity_output:             as_char
  smart_quotes:              lsquo,rsquo,ldquo,rdquo
  typographic_symbols:        {hellip: ...}
  syntax_highlighter:        rouge


# SCSS
sass:
  sass_dir:                  _sass
  style:                     :compressed
  load_paths:
    - _sass
    - assets/vendor

# Excluded files
exclude:
  - README.md
  - LICENSE
  - CNAME
  - VERSION
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - config
  - Gemfile
  - log
  - node_modules
  - package.json
  - Makefile
  - Rakefile
  - README
  - tmp
  - workbox-config.js
  - staticman.yml


keep_files:
  - .git
  - .svn

plugins:
  - jekyll-github-metadata
#  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache
  - jekyll-feed
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-github-metadata
#  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache
  - jekyll-feed

optional_front_matter:
  enabled:          false
readme_index:
  enabled:          false
titles_from_headings:
  enabled:          false
