# Develop override settings
url: http://localhost:3000
local: true

analytics:
  provider: false

sass:
  style: expanded

atom:
  buildCommand:
    - bundle
    - exec
    - jekyll
    - build
  buildEnv:
    JEKYLL_ENV: development
  postDirs:
    - _newsletters
  defaultPostDir: _drafts
  

staticman:
  endpoint               : http://localhost:8080/v2/entry/ # URL of your own deployment with trailing slash, will
